version: "3.9"
services:
  cloudflare-ddns:
    image: cloudflare-ddns
    environment:
      - HOST_NAME=
      - DOMAIN_NAME=
      - TOKEN=
    network_mode: bridge
    container_name: Cloudflare-DDNS
    restart: unless-stopped
